### Preprocessing

In [11]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.8' currently installed).
  warnings.warn(msg, UserWarning)


In [12]:
df = pd.read_csv('data/iris.csv')
df.head() #show 5 samples from head
#df.tail()  #5 samples from tail

Id  SepalLength[cm]  SepalWidth[cm]  PetalLength[cm]  PetalWidth[cm]  \
0   1              5.1             3.5              1.4             0.2   
1   2              4.9             3.0              1.4             0.2   
2   3              4.7             3.2              1.3             0.2   
3   4              4.6             3.1              1.5             0.2   
4   5              5.0             3.6              1.4             0.2   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [13]:
df.shape

(150, 6)

--------------------

.apply

In [14]:
df['Species'] = df['Species'].apply(lambda x: 0 if x=='Iris-setosa' else x)
df.head()

Id  SepalLength[cm]  SepalWidth[cm]  PetalLength[cm]  PetalWidth[cm]  \
0   1              5.1             3.5              1.4             0.2   
1   2              4.9             3.0              1.4             0.2   
2   3              4.7             3.2              1.3             0.2   
3   4              4.6             3.1              1.5             0.2   
4   5              5.0             3.6              1.4             0.2   

  Species  
0       0  
1       0  
2       0  
3       0  
4       0

.map

In [15]:
d = {'Iris-setosa':0, 
     'Iris-versicolor':1,
     'Iris-virginica' :2}

df=pd.read_csv('data/iris.csv')
df['Species'] = df['Species'].map(d)
df.head()

Id  SepalLength[cm]  SepalWidth[cm]  PetalLength[cm]  PetalWidth[cm]  \
0   1              5.1             3.5              1.4             0.2   
1   2              4.9             3.0              1.4             0.2   
2   3              4.7             3.2              1.3             0.2   
3   4              4.6             3.1              1.5             0.2   
4   5              5.0             3.6              1.4             0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0

--------

Numpy Array

In [16]:
import numpy as np
np.unique(df['Species']) #Check whether mapping is correct

array([0, 1, 2], dtype=int64)

In [17]:
y=df['Species'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [18]:
X = df.iloc[:,1:5].values #SepalLength ~ PetalWidth
X[:5] #first 5 samples 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

--------

##### Matplotlib

In [19]:
%matplotlib inline
import matplotlib.pyplot as plt
from mlxtend.data import iris_data
from mlxtend.plotting import scatterplotmatrix

ModuleNotFoundError: No module named 'mlxtend'

-------------------

##### Python Class

In [31]:
class VehicleClass():
    
    def __init__(self,horsepower):
        "this is init method"
        self.horsepower=horsepower
    
    def horsepower_to_torque(self,rpm):
        "this is regular method"
        numerator = self.horsepower*33000
        denominator = 2*np.pi*5000
        return numerator/denominator
    
    def tune_motor(self):
        self.horsepower *= 2
        
    def _private_method(self):
        print("this is private")
        
    def __very_private_method(self):
        print("this is very private")

In [32]:
car1 = VehicleClass(horsepower=123)
print(car1.horsepower)
print(car1.horsepower_to_torque(rpm=5000))
car1.tune_motor()
print(car1.horsepower)

123
129.20198280200063
246


In [33]:
car1._private_method()

this is private


In [34]:
car1.__very_private_method()

AttributeError: 'VehicleClass' object has no attribute '__very_private_method'

In [35]:
car1._VehicleClass__very_private_method()

this is very private


In [38]:
class CarClass(VehicleClass):
    
    def __init__(self,horsepower):
        super(CarClass,self).__init__(horsepower)
        self.num_wheels = 4

new_car = CarClass(horsepower=123)
print("Number of wheels:",new_car.num_wheels)
print("Horsepower:",new_car.horsepower)
new_car.tune_motor()
print("Horsepower:",new_car.horsepower)

Number of wheels: 4
Horsepower: 123
Horsepower: 246
